# Generated by Django 3.1.5 on 2021-02-13 12:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='confrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confrence_ID', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=150)),
                ('venu', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=150)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='admin-lte/images')),
                ('movie_row', models.IntegerField(default='', unique=True)),
                ('textEditor', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
