# Generated by Django 3.1.5 on 2021-02-13 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confrence',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='confrence',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
