# Generated by Django 3.1.5 on 2021-02-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0002_auto_20210213_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confrence',
            old_name='movie_row',
            new_name='contact_detail',
        ),
    ]
