# Generated by Django 3.1.6 on 2021-02-15 09:31

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0003_auto_20210213_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confrence',
            old_name='textEditor',
            new_name='confrence_Overview',
        ),
        migrations.RemoveField(
            model_name='confrence',
            name='city',
        ),
        migrations.RemoveField(
            model_name='confrence',
            name='contact_detail',
        ),
        migrations.RemoveField(
            model_name='confrence',
            name='email',
        ),
        migrations.RemoveField(
            model_name='confrence',
            name='name',
        ),
        migrations.AddField(
            model_name='confrence',
            name='registration',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
