# Generated by Django 3.1.7 on 2021-02-23 12:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='confrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confrence_ID', models.CharField(default='', max_length=20)),
                ('date', models.DateTimeField()),
                ('venu', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='admin-lte/images')),
                ('confrence_Overview', ckeditor.fields.RichTextField()),
                ('registration', ckeditor.fields.RichTextField()),
                ('travel_information', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
